%Load the raw data
xg = '/Users/zhengwei/Desktop/X_Gyroscope.csv';
X_G = csvread(xg);
yg = '/Users/zhengwei/Desktop/Y_Gyroscope.csv';
Y_G = csvread(yg);
zg = '/Users/zhengwei/Desktop/Z_Gyroscope.csv';
Z_G = csvread(zg);
xa = '/Users/zhengwei/Desktop/X_Accelerometer.csv';
X_A = csvread(xa);
ya = '/Users/zhengwei/Desktop/Y_Accelerometer.csv';
Y_A = csvread(ya);
za = '/Users/zhengwei/Desktop/Z_Accelerometer.csv';
Z_A = csvread(za);

%Plot the 6-axis raw data (each pick 3 examples)
k = 1:80;
figure(1);
plot(k,X_A(4,:),'r');
hold on;
plot(k,X_A(5,:),'b');
hold on;
plot(k,X_A(6,:),'g');
hold on;
xlabel('time/20ms');
ylabel('Accelerometer');
title('Fall X_A');
saveas(gcf,'/Users/zhengwei/Desktop/Fall_XA.png');

figure(2);
plot(k,X_A(11,:),'r');
hold on;
plot(k,X_A(12,:),'b');
hold on;
plot(k,X_A(13,:),'g');
hold on;
xlabel('time/20ms');
ylabel('Accelerometer');
title('Walk X_A');
saveas(gcf,'/Users/zhengwei/Desktop/Walk_XA.png');

figure(3);
plot(k,X_G(4,:),'r');
hold on;
plot(k,X_G(5,:),'b');
hold on;
plot(k,X_G(6,:),'g');
hold on;
xlabel('time/20ms');
ylabel('Accelerometer');
title('Fall X_G');
saveas(gcf,'/Users/zhengwei/Desktop/Fall_XG.png');

figure(4);
plot(k,X_G(11,:),'r');
hold on;
plot(k,X_G(12,:),'b');
hold on;
plot(k,X_G(13,:),'g');
hold on;
xlabel('time/20ms');
ylabel('Accelerometer');
title('Walk X_G');
saveas(gcf,'/Users/zhengwei/Desktop/Walk_XG.png');

figure(5);
plot(k,Y_A(4,:),'r');
hold on;
plot(k,Y_A(5,:),'b');
hold on;
plot(k,Y_A(6,:),'g');
hold on;
xlabel('time/20ms');
ylabel('Accelerometer');
title('Fall Y_A');
saveas(gcf,'/Users/zhengwei/Desktop/Fall_YA.png');

figure(6);
plot(k,Y_A(11,:),'r');
hold on;
plot(k,Y_A(12,:),'b');
hold on;
plot(k,Y_A(13,:),'g');
hold on;
xlabel('time/20ms');
ylabel('Accelerometer');
title('Walk Y_A');
saveas(gcf,'/Users/zhengwei/Desktop/Walk_YA.png');

figure(7);
plot(k,Y_G(4,:),'r');
hold on;
plot(k,Y_G(5,:),'b');
hold on;
plot(k,Y_G(6,:),'g');
hold on;
xlabel('time/20ms');
ylabel('Accelerometer');
title('Fall Y_G');
saveas(gcf,'/Users/zhengwei/Desktop/Fall_YG.png');

figure(8);
plot(k,Y_G(11,:),'r');
hold on;
plot(k,Y_G(12,:),'b');
hold on;
plot(k,Y_G(13,:),'g');
hold on;
xlabel('time/20ms');
ylabel('Accelerometer');
title('Walk Y_G');
saveas(gcf,'/Users/zhengwei/Desktop/Walk_YG.png');

figure(9);
plot(k,Z_A(4,:),'r');
hold on;
plot(k,Z_A(5,:),'b');
hold on;
plot(k,Z_A(6,:),'g');
hold on;
xlabel('time/20ms');
ylabel('Accelerometer');
title('Fall Z_A');
saveas(gcf,'/Users/zhengwei/Desktop/Fall_ZA.png');

figure(10);
plot(k,Z_A(11,:),'r');
hold on;
plot(k,Z_A(12,:),'b');
hold on;
plot(k,Z_A(13,:),'g');
hold on;
xlabel('time/20ms');
ylabel('Accelerometer');
title('Walk Z_A');
saveas(gcf,'/Users/zhengwei/Desktop/Walk_ZA.png');

figure(11);
plot(k,Z_G(4,:),'r');
hold on;
plot(k,Z_G(5,:),'b');
hold on;
plot(k,Z_G(6,:),'g');
hold on;
xlabel('time/20ms');
ylabel('Accelerometer');
title('Fall Z_G');
saveas(gcf,'/Users/zhengwei/Desktop/Fall_ZG.png');

figure(12);
plot(k,Z_G(11,:),'r');
hold on;
plot(k,Z_G(12,:),'b');
hold on;
plot(k,Z_G(13,:),'g');
hold on;
xlabel('time/20ms');
ylabel('Accelerometer');
title('Walk Z_G');
saveas(gcf,'/Users/zhengwei/Desktop/Walk_ZG.png');